BEGIN;
DROP TABLE IF EXISTS public.trecord CASCADE;
DROP TABLE IF EXISTS public.category CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TABLE IF EXISTS public.currency CASCADE;
DROP TABLE IF EXISTS public.user CASCADE;
COMMIT;