CREATE TABLE IF NOT EXISTS public.trecord (
  uuid TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  amount MONEY NOT NULL,
  currency TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)